spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=filmorate
spring.datasource.password=filmorate
spring.sql.int.schema-location=classpath:shema.sql
sprint.sql.int.data-location=classpath:data.sql
